// dashboard/frontend/src/features/monitor/nodes/nodes.component.ts
import { LitElement, html } from "lit";
import { customElement, state } from "lit/decorators.js";
import { store } from "@/core/store/store";
import { createLocaleController } from "@/core/store/locale-controller";
import { LitStoreController, shallowEqual } from "@/core/store/lit-store-controller";
import { selectBrStatus, selectChildTable, selectOtConfig, selectRouterTable, selectThreadState } from "@/core/store/selectors";
import { appBarActions } from "@/core/store/slices/appbar.slice";
import { t } from "@/core/i18n/i18n";

import "@/core/components/modal/modal.component";
import "@monitor/nodes/nodes.style.scss";

function normCol(name: string): string {
  return String(name).trim().toLowerCase();
}

function colIndex(headers: string[] | undefined, name: string): number {
  if (!headers?.length) return -1;
  const n = normCol(name);
  return headers.findIndex((h) => normCol(h) === n);
}

function linkQualityToPercent(cell: string): number {
  const v = parseInt(cell, 10);
  if (Number.isNaN(v)) return 0;
  return Math.round((Math.min(3, Math.max(0, v)) / 3) * 100);
}

function linkQualityBarClass(percent: number): string {
  if (percent >= 80) return "nodes-link-quality-bar-fill--good";
  if (percent >= 50) return "nodes-link-quality-bar-fill--mid";
  return "nodes-link-quality-bar-fill--warn";
}

type SelectedRow = { type: "router"; rowIndex: number } | { type: "child"; rowIndex: number };

@customElement("nodes-view")
export class NodesComponent extends LitElement {
  override createRenderRoot() {
    return this;
  }

  private readonly locale = createLocaleController(this);

  private readonly appState = new LitStoreController(
    this,
    store,
    (s) => ({
      isConnected: selectBrStatus(s)?.isConnected ?? false,
      routerTable: selectRouterTable(s),
      childTable: selectChildTable(s),
      otConfig: selectOtConfig(s),
      threadState: selectThreadState(s),
    }),
    shallowEqual
  );

  @state() private selectedRow: SelectedRow | null = null;
  @state() private routerAgeOffsets: number[] = [];
  @state() private childAgeOffsets: number[] = [];
  private _lastAppBarSig = "";

  private _routerRowsRef: string[][] | null = null;
  private _childRowsRef: string[][] | null = null;
  private _routerTick: ReturnType<typeof setInterval> | null = null;
  private _childTick: ReturnType<typeof setInterval> | null = null;

  override willUpdate(_changed: Map<string, unknown>) {
    const { routerTable, childTable } = this.appState.value;
    const routerRows = routerTable?.rows ?? [];
    const childRows = childTable?.rows ?? [];
    const rH = routerTable?.headers ?? [];
    const cH = childTable?.headers ?? [];
    const rAge = colIndex(rH, "Age");
    const cAge = colIndex(cH, "Age");

    if (rAge >= 0 && routerRows.length > 0) {
      if (this._routerRowsRef !== routerRows) {
        this._routerRowsRef = routerRows;
        this.routerAgeOffsets = new Array(routerRows.length).fill(0);
      }
    } else if (rAge < 0 || routerRows.length === 0) {
      this.routerAgeOffsets = [];
      this._routerRowsRef = null;
    }

    if (cAge >= 0 && childRows.length > 0) {
      if (this._childRowsRef !== childRows) {
        this._childRowsRef = childRows;
        this.childAgeOffsets = new Array(childRows.length).fill(0);
      }
    } else if (cAge < 0 || childRows.length === 0) {
      this.childAgeOffsets = [];
      this._childRowsRef = null;
    }
  }

  override updated(_changed: Map<string, unknown>) {
    const { routerTable, childTable } = this.appState.value;
    const rH = routerTable?.headers ?? [];
    const cH = childTable?.headers ?? [];
    const rAge = colIndex(rH, "Age");
    const cAge = colIndex(cH, "Age");
    const routerRows = routerTable?.rows ?? [];
    const childRows = childTable?.rows ?? [];

    if (rAge >= 0 && routerRows.length > 0) {
      if (!this._routerTick) {
        this._routerTick = setInterval(() => {
          this.routerAgeOffsets = this.routerAgeOffsets.map((v) => v + 1);
        }, 1000);
      }
    } else if (this._routerTick) {
      clearInterval(this._routerTick);
      this._routerTick = null;
    }

    if (cAge >= 0 && childRows.length > 0) {
      if (!this._childTick) {
        this._childTick = setInterval(() => {
          this.childAgeOffsets = this.childAgeOffsets.map((v) => v + 1);
        }, 1000);
      }
    } else if (this._childTick) {
      clearInterval(this._childTick);
      this._childTick = null;
    }
  }

  override disconnectedCallback() {
    if (this._routerTick) clearInterval(this._routerTick);
    if (this._childTick) clearInterval(this._childTick);
    store.dispatch(appBarActions.clearAppBar());
    super.disconnectedCallback();
  }

  private _linkQualityBarCell(value: string) {
    const percent = linkQualityToPercent(value);
    const fillClass = linkQualityBarClass(percent);
    return html`
      <div class="nodes-link-quality-bar-cell">
        <div class="nodes-link-quality-bar-track">
          <div class="nodes-link-quality-bar-fill ${fillClass}" style="width: ${percent}%"></div>
        </div>
        <span class="nodes-link-quality-bar-num">${percent}</span>
      </div>
    `;
  }

  private _linkQualityBarsCell(value: string) {
    const n = Math.min(4, Math.max(0, parseInt(value, 10) || 0));
    return html`
      <div class="nodes-link-quality-bars-cell">
        <div class="nodes-link-quality-bars">
          ${[0, 1, 2, 3].map((i) => html`<div class="nodes-link-quality-bar-v ${i < n ? "nodes-link-quality-bar-v--filled" : ""}"></div>`)}
        </div>
        <span class="nodes-link-quality-bars-num">${n}</span>
      </div>
    `;
  }

  render() {
    void this.locale.value;
    const appBar = {
      heading: t("nodes.header.title"),
      subtitle: t("nodes.header.subtitle"),
      actions: [],
    };
    const sig = JSON.stringify(appBar);
    if (sig !== this._lastAppBarSig) {
      this._lastAppBarSig = sig;
      store.dispatch(appBarActions.setAppBar(appBar));
    }
    const { isConnected, routerTable, childTable, otConfig } = this.appState.value;
    const rH = routerTable?.headers ?? [];
    const cH = childTable?.headers ?? [];
    const rRouterId = colIndex(rH, "RouterId");
    const rRloc16 = colIndex(rH, "RLOC16");
    const rExtAddress = colIndex(rH, "ExtAddress");
    const rLqIn = colIndex(rH, "LinkQualityIn");
    const rLqOut = colIndex(rH, "LinkQualityOut");
    const rAge = colIndex(rH, "Age");
    const cChildId = colIndex(cH, "ChildId");
    const cRloc16 = colIndex(cH, "RLOC16");
    const cExtAddress = colIndex(cH, "ExtAddress");
    const cLqIn = colIndex(cH, "LinkQualityIn");
    const cAvgRssi = colIndex(cH, "AverageRssi");
    const cFtd = colIndex(cH, "FullThreadDevice");
    const cRxOnIdle = colIndex(cH, "RxOnWhenIdle");
    const cAge = colIndex(cH, "Age");

    const routerRows = routerTable?.rows ?? [];
    const childRows = childTable?.rows ?? [];
    const leaderRloc16 = otConfig?.leaderRloc16 ?? null;

    const tableForRow = this.selectedRow?.type === "router" ? routerTable : childTable;
    const selectedRowData =
      this.selectedRow != null && tableForRow?.headers?.length && tableForRow.rows?.[this.selectedRow.rowIndex]
        ? tableForRow.rows[this.selectedRow.rowIndex]
        : null;
    const rloc16Index = tableForRow?.headers?.findIndex((h) => normCol(h) === "rloc16") ?? -1;
    const rloc16Value = selectedRowData && rloc16Index >= 0 ? selectedRowData[rloc16Index] ?? "" : "";
    const tableLabel = this.selectedRow?.type === "router" ? t("nodes.routerTable.title") : t("nodes.childTable.title");
    const modalTitle = this.selectedRow == null ? "" : `${tableLabel} - ${rloc16Value}`;
    const modalEntries: { key: string; value: string }[] = [];
    if (this.selectedRow != null && tableForRow?.headers?.length && selectedRowData) {
      tableForRow.headers.forEach((h, i) => {
        modalEntries.push({ key: h, value: selectedRowData[i] ?? "" });
      });
    }

    return html`
      <div class="page-container">
        <div class="nodes-page">
          <section class="nodes-section">
            <h2 class="nodes-section-title">
              <span class="material-symbols-outlined nodes-section-icon">router</span>
              ${t("nodes.routerTable.title")}
            </h2>
            <div class="nodes-table-wrap">
              <table class="nodes-table">
                <thead>
                  <tr>
                    <th>${t("nodes.routerTable.columns.routerId")}</th>
                    <th>${t("nodes.common.columns.rloc16")}</th>
                    <th>${t("nodes.common.columns.extAddress")}</th>
                    <th>${t("nodes.routerTable.columns.linkQualityIn")}</th>
                    <th>${t("nodes.routerTable.columns.linkQualityOut")}</th>
                    <th>${t("nodes.common.columns.age")}</th>
                  </tr>
                </thead>
                <tbody>
                  ${!isConnected ? html `
                    <tr class="nodes-row-empty">
                      <td class="nodes-cell-empty nodes-muted" colspan="6">
                        ${t("nodes.common.empty.connectToBr")}
                      </td>
                    </tr>
                  ` : routerTable?.error ? html `
                    <tr class="nodes-row-empty">
                      <td class="nodes-cell-empty nodes-error" colspan="6">
                        ${routerTable.error}
                      </td>
                    </tr>
                  ` : routerTable == null || routerRows.length === 0 ? html `
                    <tr class="nodes-row-empty">
                      <td class="nodes-cell-empty nodes-muted" colspan="6">
                        ${t("nodes.routerTable.empty.none")}
                      </td>
                    </tr>
                  ` : routerRows.map((row, ri) => {
                    const rloc16 = rRloc16 >= 0 ? row[rRloc16] ?? "" : "";
                    const isLeader = leaderRloc16 != null && rloc16.toLowerCase() === leaderRloc16.toLowerCase();
                    const baseAge = rAge >= 0 ? parseInt(row[rAge] ?? "0", 10) : 0;
                    const ageSec = baseAge + (this.routerAgeOffsets[ri] ?? 0);
                    return html`
                      <tr class="${isLeader ? "nodes-table-row-leader" : ""}" @click=${() => (this.selectedRow = { type: "router", rowIndex: ri })}>
                        <td class="nodes-cell-id">
                          <span class="nodes-cell-id-main">${rRouterId >= 0 ? row[rRouterId] : ""}</span>
                          ${isLeader ? html`<span class="nodes-leader-badge">${t("nodes.common.badges.leader")}</span>` : ""}
                        </td>
                        <td class="nodes-cell-mono">${rRloc16 >= 0 ? row[rRloc16] : ""}</td>
                        <td class="nodes-cell-mono">${rExtAddress >= 0 ? row[rExtAddress] : ""}</td>
                        <td>${this._linkQualityBarCell(rLqIn >= 0 ? row[rLqIn] : "")}</td>
                        <td>${this._linkQualityBarCell(rLqOut >= 0 ? row[rLqOut] : "")}</td>
                        <td class="nodes-cell-age">${ageSec}s</td>
                      </tr>
                    `;
                  })}
                </tbody>
              </table>
            </div>
          </section>

          <section class="nodes-section">
            <h2 class="nodes-section-title">
              <span class="material-symbols-outlined nodes-section-icon">account_tree</span>
              ${t("nodes.childTable.title")}
            </h2>
            <div class="nodes-table-wrap">
              <table class="nodes-table">
                <thead>
                  <tr>
                    <th>${t("nodes.childTable.columns.childId")}</th>
                    <th>${t("nodes.common.columns.rloc16")}</th>
                    <th>${t("nodes.common.columns.extAddress")}</th>
                    <th>${t("nodes.childTable.columns.lqIn")}</th>
                    <th>${t("nodes.childTable.columns.avgRssi")}</th>
                    <th class="nodes-th-center">FTD</th>
                    <th class="nodes-th-center">RxOnIdle</th>
                    <th>${t("nodes.common.columns.age")}</th>
                  </tr>
                </thead>
                <tbody>
                  ${!isConnected ? html `
                    <tr class="nodes-row-empty">
                      <td class="nodes-cell-empty nodes-muted" colspan="8">
                        ${t("nodes.common.empty.connectToBr")}
                      </td>
                    </tr>
                  ` : childTable?.error ? html `
                    <tr class="nodes-row-empty">
                      <td class="nodes-cell-empty nodes-error" colspan="8">
                        ${childTable.error}
                      </td>
                    </tr>
                  ` : childTable == null || childRows.length === 0 ? html `
                  <tr class="nodes-row-empty">
                      <td class="nodes-cell-empty nodes-muted" colspan="8">\
                        ${t("nodes.childTable.empty.none")}
                      </td>
                    </tr>
                  ` : childRows.map((row, ri) => {
                    const baseAge = cAge >= 0 ? parseInt(row[cAge] ?? "0", 10) : 0;
                    const ageSec = baseAge + (this.childAgeOffsets[ri] ?? 0);
                    const ftdVal = cFtd >= 0 ? row[cFtd] ?? "" : "";
                    const rxVal = cRxOnIdle >= 0 ? row[cRxOnIdle] ?? "" : "";
                    return html`
                      <tr @click=${() => (this.selectedRow = { type: "child", rowIndex: ri })}>
                        <td class="nodes-cell-id">${cChildId >= 0 ? row[cChildId] : ""}</td>
                        <td class="nodes-cell-mono">${cRloc16 >= 0 ? row[cRloc16] : ""}</td>
                        <td class="nodes-cell-mono">${cExtAddress >= 0 ? row[cExtAddress] : ""}</td>
                        <td>${this._linkQualityBarsCell(cLqIn >= 0 ? row[cLqIn] : "")}</td>
                        <td class="nodes-cell-rssi">${cAvgRssi >= 0 ? row[cAvgRssi] : ""}</td>
                        <td class="nodes-cell-icon">
                          ${ftdVal === "FTD"
                            ? html`<span class="material-symbols-outlined nodes-icon-ok">check_circle</span>`
                            : html`<span class="material-symbols-outlined nodes-icon-no">cancel</span>`}
                        </td>
                        <td class="nodes-cell-icon">
                          ${rxVal === "Yes"
                            ? html`<span class="material-symbols-outlined nodes-icon-ok">check_circle</span>`
                            : html`<span class="material-symbols-outlined nodes-icon-no">cancel</span>`}
                        </td>
                        <td class="nodes-cell-age">${ageSec}s</td>
                      </tr>
                    `;
                  })}
                </tbody>
              </table>
            </div>
          </section>

          <modal-dialog
            .open=${this.selectedRow != null}
            .title=${modalTitle}
            .body=${html`
              <ul class="nodes-modal-detail-list">
                ${modalEntries.map(({ key: fieldKey, value }) => html`
                  <li>
                    <span class="nodes-modal-detail-key">${fieldKey}</span>
                    <span class="nodes-modal-detail-value">${value}</span>
                  </li>
                `)}
              </ul>
            `}
            .onClose=${() => (this.selectedRow = null)}
          ></modal-dialog>
        </div>
      </div>
    `;
  }

}

declare global {
  interface HTMLElementTagNameMap {
    "nodes-view": NodesComponent;
  }
}

// Dashboard-Thread/frontend/src/components/Nodes/Nodes.tsx
import { useEffect, useMemo, useRef, useState } from "react";
import { useWebSocketContext } from "../../hooks/useWebSocketContext";
import Modal from "../common/Modal";
import CommissionNodeModal from "./CommissionNodeModal";
import JoinerList from "./JoinerList";
import "./Nodes.scss";

/** Chuẩn hóa tên cột để so khớp (trim, lowercase) */
function normCol(name: string): string {
  return String(name).trim().toLowerCase();
}

/** Lấy index cột từ headers (không phân biệt hoa thường). */
function colIndex(headers: string[] | undefined, name: string): number {
  if (!headers?.length) return -1;
  const n = normCol(name);
  const i = headers.findIndex((h) => normCol(h) === n);
  return i >= 0 ? i : -1;
}

/** Backend LQ 0–3 → percent 0–100. */
function lqToPercent(cell: string): number {
  const v = parseInt(cell, 10);
  if (Number.isNaN(v)) return 0;
  return Math.round((Math.min(3, Math.max(0, v)) / 3) * 100);
}

/** Bar color class by percent: green >= 80, primary >= 50, else amber. */
function lqBarClass(percent: number): string {
  if (percent >= 80) return "nodes-lq-bar-fill--good";
  if (percent >= 50) return "nodes-lq-bar-fill--mid";
  return "nodes-lq-bar-fill--warn";
}

type TableData = { headers?: string[]; rows?: string[][]; error?: string } | null;
type SelectedRow = { type: "router"; rowIndex: number } | { type: "child"; rowIndex: number };

export default function Nodes() {
  const {
    serialStatus,
    otConfig,
    testBrConnect,
    routerTable,
    childTable,
    joinerTable,
    getRouterTable,
    getChildTable,
    getJoinerTable,
  } = useWebSocketContext();
  const isConnected = serialStatus?.isConnected ?? false;
  const [selectedRow, setSelectedRow] = useState<SelectedRow | null>(null);
  const [isCommissionModalOpen, setCommissionModalOpen] = useState(false);

  const routerLoading = isConnected && routerTable === null;
  const childLoading = isConnected && childTable === null;
  const routerCount = routerTable?.rows?.length ?? 0;
  const childCount = childTable?.rows?.length ?? 0;

  // Column indices for router table (backend: RouterId, RLOC16, ExtAddress, LinkQualityIn, LinkQualityOut, Age)
  const rH = routerTable?.headers ?? [];
  const rRouterId = colIndex(rH, "RouterId");
  const rRloc16 = colIndex(rH, "RLOC16");
  const rExtAddress = colIndex(rH, "ExtAddress");
  const rLqIn = colIndex(rH, "LinkQualityIn");
  const rLqOut = colIndex(rH, "LinkQualityOut");
  const rAge = colIndex(rH, "Age");

  // Column indices for child table
  const cH = childTable?.headers ?? [];
  const cChildId = colIndex(cH, "ChildId");
  const cRloc16 = colIndex(cH, "RLOC16");
  const cExtAddress = colIndex(cH, "ExtAddress");
  const cLqIn = colIndex(cH, "LinkQualityIn");
  const cAvgRssi = colIndex(cH, "AverageRssi");
  const cFtd = colIndex(cH, "FullThreadDevice");
  const cRxOnIdle = colIndex(cH, "RxOnWhenIdle");
  const cAge = colIndex(cH, "Age");

  // Age offsets for live "Xs" display
  const [routerAgeOffsets, setRouterAgeOffsets] = useState<number[]>([]);
  const [childAgeOffsets, setChildAgeOffsets] = useState<number[]>([]);
  const routerRowsRef = useRef<string[][] | null>(null);
  const childRowsRef = useRef<string[][] | null>(null);

  const routerRows = routerTable?.rows ?? [];
  const childRows = childTable?.rows ?? [];

  useEffect(() => {
    if (rAge < 0 || routerRows.length === 0) {
      setRouterAgeOffsets([]);
      routerRowsRef.current = null;
      return;
    }
    if (routerRowsRef.current !== routerRows) {
      routerRowsRef.current = routerRows;
      setRouterAgeOffsets(new Array(routerRows.length).fill(0));
    }
  }, [routerRows, rAge]);

  useEffect(() => {
    if (cAge < 0 || childRows.length === 0) {
      setChildAgeOffsets([]);
      childRowsRef.current = null;
      return;
    }
    if (childRowsRef.current !== childRows) {
      childRowsRef.current = childRows;
      setChildAgeOffsets(new Array(childRows.length).fill(0));
    }
  }, [childRows, cAge]);

  useEffect(() => {
    if (rAge < 0 || routerRows.length === 0) return;
    const t = setInterval(() => setRouterAgeOffsets((prev) => prev.map((v) => v + 1)), 1000);
    return () => clearInterval(t);
  }, [rAge, routerRows.length]);

  useEffect(() => {
    if (cAge < 0 || childRows.length === 0) return;
    const t = setInterval(() => setChildAgeOffsets((prev) => prev.map((v) => v + 1)), 1000);
    return () => clearInterval(t);
  }, [cAge, childRows.length]);

  const leaderRloc16 = otConfig?.leaderRloc16 ?? null;
  const showDisconnectedOverlay = !isConnected;

  const tableForRow = selectedRow?.type === "router" ? routerTable : childTable;
  const selectedRowData =
    selectedRow != null && tableForRow?.headers?.length && tableForRow.rows?.[selectedRow.rowIndex]
      ? tableForRow.rows[selectedRow.rowIndex]
      : null;
  const rloc16Index =
    tableForRow?.headers?.findIndex((h) => normCol(h) === "rloc16") ?? -1;
  const rloc16Value = selectedRowData && rloc16Index >= 0 ? selectedRowData[rloc16Index] ?? "" : "";
  const tableLabel = selectedRow?.type === "router" ? "Router Table" : "Child Table";
  const modalTitle =
    selectedRow == null ? "" : `${tableLabel} - ${rloc16Value}`;
  const modalEntries: { key: string; value: string }[] = [];
  if (selectedRow != null && tableForRow?.headers?.length && selectedRowData) {
    tableForRow.headers.forEach((h, i) => {
      modalEntries.push({ key: h, value: selectedRowData[i] ?? "" });
    });
  }

  const hasRouterData =
    routerTable && !routerTable.error && (rH.length > 0 || routerRows.length > 0);
  const hasChildData =
    childTable && !childTable.error && (cH.length > 0 || childRows.length > 0);

  const handleTryReconnect = () => void testBrConnect({ brHost: "", brPort: 5000 });

  return (
    <div className="nodes-page">
      {showDisconnectedOverlay && (
        <div className="nodes-disconnected-overlay">
          <div className="nodes-disconnected-card">
            <div className="nodes-disconnected-icon">
              <span className="material-symbols-outlined">wifi_off</span>
            </div>
            <h1 className="nodes-disconnected-title">Border Router Disconnected</h1>
            <p className="nodes-disconnected-text">
              Connect to the Border Router to view network topology and node information.
            </p>
            <button
              type="button"
              className="nodes-disconnected-btn"
              onClick={handleTryReconnect}
            >
              <span className="material-symbols-outlined">refresh</span>
              <span>Try Reconnecting</span>
            </button>
          </div>
        </div>
      )}

      <div className="nodes-content">
        <div className="nodes-header">
          <div className="nodes-header-text">
            <h1 className="nodes-title">Nodes</h1>
            <p className="nodes-subtitle">
              Manage and monitor network topology and connectivity
            </p>
          </div>
          <button
            type="button"
            className="nodes-btn-commission"
            onClick={() => setCommissionModalOpen(true)}
          >
            <span className="material-symbols-outlined">add_circle</span>
            <span>Commission Node</span>
          </button>
        </div>

        <section className="nodes-section">
        <h2 className="nodes-section-title">
          <span className="material-symbols-outlined nodes-section-icon">router</span>
          Router Table
        </h2>
        <div className="nodes-table-wrap">
          {showDisconnectedOverlay ? (
            <p className="nodes-muted">Loading…</p>
          ) : routerTable?.error ? (
            <p className="nodes-error">{routerTable.error}</p>
          ) : routerLoading && !hasRouterData ? (
            <p className="nodes-muted">Loading…</p>
          ) : !hasRouterData ? (
            <p className="nodes-muted">No routers found in the network.</p>
          ) : (
            <table className="nodes-table">
              <thead>
                <tr>
                  <th>Router ID</th>
                  <th>RLOC16</th>
                  <th>Ext Address</th>
                  <th>Link Quality In</th>
                  <th>Link Quality Out</th>
                  <th>Age</th>
                </tr>
              </thead>
              <tbody>
                {routerRows.length === 0 ? (
                  <tr className="nodes-row-empty">
                    <td className="nodes-cell-empty" colSpan={6}>
                      No routers found in the network.
                    </td>
                  </tr>
                ) : (
                  routerRows.map((row, ri) => {
                    const rloc16 = rRloc16 >= 0 ? row[rRloc16] ?? "" : "";
                    const isLeader =
                      leaderRloc16 != null &&
                      rloc16.toLowerCase() === leaderRloc16.toLowerCase();
                    const baseAge = rAge >= 0 ? parseInt(row[rAge] ?? "0", 10) : 0;
                    const ageSec = Number.isNaN(baseAge)
                      ? 0
                      : baseAge + (routerAgeOffsets[ri] ?? 0);
                    const routerKey = rloc16 || `router-${rExtAddress >= 0 ? row[rExtAddress] ?? ri : ri}`;
                    return (
                      <tr
                        key={routerKey}
                        className={isLeader ? "nodes-table-row-leader" : ""}
                        onClick={() => setSelectedRow({ type: "router", rowIndex: ri })}
                      >
                        <td className="nodes-cell-id">
                          <span className="nodes-cell-id-main">
                            {rRouterId >= 0 ? row[rRouterId] : ""}
                          </span>
                          {isLeader && (
                            <span className="nodes-leader-badge">LEADER</span>
                          )}
                        </td>
                        <td className="nodes-cell-mono">{rRloc16 >= 0 ? row[rRloc16] : ""}</td>
                        <td className="nodes-cell-mono">{rExtAddress >= 0 ? row[rExtAddress] : ""}</td>
                        <td>
                          <LqBarCell value={rLqIn >= 0 ? row[rLqIn] : ""} />
                        </td>
                        <td>
                          <LqBarCell value={rLqOut >= 0 ? row[rLqOut] : ""} />
                        </td>
                        <td className="nodes-cell-age">{ageSec}s</td>
                      </tr>
                    );
                  })
                )}
              </tbody>
            </table>
          )}
        </div>
      </section>

        <section className="nodes-section">
        <h2 className="nodes-section-title">
          <span className="material-symbols-outlined nodes-section-icon">account_tree</span>
          Child Table
        </h2>
        <div className="nodes-table-wrap">
          {showDisconnectedOverlay ? (
            <p className="nodes-muted">Loading…</p>
          ) : childTable?.error ? (
            <p className="nodes-error">{childTable.error}</p>
          ) : childLoading && !hasChildData ? (
            <p className="nodes-muted">Loading…</p>
          ) : !hasChildData ? (
            <p className="nodes-muted">No child nodes connected.</p>
          ) : (
            <table className="nodes-table">
              <thead>
                <tr>
                  <th>Child ID</th>
                  <th>RLOC16</th>
                  <th>Ext Address</th>
                  <th>LQ In</th>
                  <th>Avg RSSI</th>
                  <th className="nodes-th-center">FTD</th>
                  <th className="nodes-th-center">RxOnIdle</th>
                  <th>Age</th>
                </tr>
              </thead>
              <tbody>
                {childRows.length === 0 ? (
                  <tr className="nodes-row-empty">
                    <td className="nodes-cell-empty" colSpan={8}>
                      No child nodes connected.
                    </td>
                  </tr>
                ) : (
                  childRows.map((row, ri) => {
                    const childRloc = cRloc16 >= 0 ? row[cRloc16] ?? "" : "";
                    const childExt = cExtAddress >= 0 ? row[cExtAddress] ?? "" : "";
                    const childKey = childRloc || childExt || `child-${ri}`;
                    const baseAge = cAge >= 0 ? parseInt(row[cAge] ?? "0", 10) : 0;
                    const ageSec = Number.isNaN(baseAge)
                      ? 0
                      : baseAge + (childAgeOffsets[ri] ?? 0);
                    const ftdVal = cFtd >= 0 ? row[cFtd] ?? "" : "";
                    const rxVal = cRxOnIdle >= 0 ? row[cRxOnIdle] ?? "" : "";
                    return (
                      <tr
                        key={childKey}
                        onClick={() => setSelectedRow({ type: "child", rowIndex: ri })}
                      >
                        <td className="nodes-cell-id">{cChildId >= 0 ? row[cChildId] : ""}</td>
                        <td className="nodes-cell-mono">{cRloc16 >= 0 ? row[cRloc16] : ""}</td>
                        <td className="nodes-cell-mono">{cExtAddress >= 0 ? row[cExtAddress] : ""}</td>
                        <td>
                          <LqBarsCell value={cLqIn >= 0 ? row[cLqIn] : ""} />
                        </td>
                        <td className="nodes-cell-rssi">{cAvgRssi >= 0 ? row[cAvgRssi] : ""}</td>
                        <td className="nodes-cell-icon">
                          {ftdVal === "FTD" ? (
                            <span className="material-symbols-outlined nodes-icon-ok">check_circle</span>
                          ) : (
                            <span className="material-symbols-outlined nodes-icon-no">cancel</span>
                          )}
                        </td>
                        <td className="nodes-cell-icon">
                          {rxVal === "Yes" ? (
                            <span className="material-symbols-outlined nodes-icon-ok">check_circle</span>
                          ) : (
                            <span className="material-symbols-outlined nodes-icon-no">cancel</span>
                          )}
                        </td>
                        <td className="nodes-cell-age">{ageSec}s</td>
                      </tr>
                    );
                  })
                )}
              </tbody>
            </table>
          )}
        </div>
      </section>

        <JoinerList
          joinerTable={joinerTable}
          getJoinerTable={getJoinerTable}
          isConnected={isConnected}
        />

        <Modal
          open={selectedRow != null}
          onClose={() => setSelectedRow(null)}
          title={modalTitle}
        >
          <ul className="modal-detail-list">
            {modalEntries.map(({ key: fieldKey, value }) => (
              <li key={fieldKey}>
                <span className="modal-detail-key">{fieldKey}</span>
                <span className="modal-detail-value">{value}</span>
              </li>
            ))}
          </ul>
        </Modal>

        <CommissionNodeModal
          open={isCommissionModalOpen}
          onClose={() => setCommissionModalOpen(false)}
        />
      </div>
    </div>
  );
}

function LqBarCell({ value }: { value: string }) {
  const percent = lqToPercent(value);
  const fillClass = lqBarClass(percent);
  return (
    <div className="nodes-lq-bar-cell">
      <div className="nodes-lq-bar-track">
        <div
          className={`nodes-lq-bar-fill ${fillClass}`}
          style={{ width: `${percent}%` }}
        />
      </div>
      <span className="nodes-lq-bar-num">{percent}</span>
    </div>
  );
}

function LqBarsCell({ value }: { value: string }) {
  const n = Math.min(4, Math.max(0, parseInt(value, 10) || 0));
  return (
    <div className="nodes-lq-bars-cell">
      <div className="nodes-lq-bars">
        {[0, 1, 2, 3].map((i) => (
          <div
            key={`lq-bar-${i}`}
            className={`nodes-lq-bar-v ${i < n ? "nodes-lq-bar-v--filled" : ""}`}
          />
        ))}
      </div>
      <span className="nodes-lq-bars-num">{n}</span>
    </div>
  );
}
