// dashboard/frontend/src/core/components/sidebar/sidebar.component.ts
import { LitElement, html } from "lit";
import { customElement, property } from "lit/decorators.js";
import type { NavPage } from "@/core/types/nav.type";
import { store } from "@/core/store/store";
import { createLocaleController } from "@/core/store/locale-controller";
import { LitStoreController, shallowEqual } from "@/core/store/lit-store-controller";
import {
  selectBrStatus,
  selectChildTable,
  selectRouterTable,
  selectThreadRunOnConnect,
  selectThreadState,
} from "@/core/store/selectors";
import { t } from "@/core/i18n/i18n";

import "@core/components/sidebar/sidebar.style.scss";

interface NavItem {
  page: NavPage;
  label: string;
  icon: string;
}

interface NavGroup {
  label: string;
  items: NavItem[];
}

const NAV_ITEMS: NavGroup[] = [
  {
    label: "sidebar.group.monitor",
    items: [
      { page: "monitor-status", label: "sidebar.item.status", icon: "speed" },
      { page: "monitor-nodes", label: "sidebar.item.nodes", icon: "account_tree" },
      { page: "monitor-joiner", label: "sidebar.item.joiner", icon: "group_add" },
      { page: "monitor-topology", label: "sidebar.item.topology", icon: "hub" },
    ],
  },
  {
    label: "sidebar.group.settings",
    items: [
      { page: "settings-connection", label: "sidebar.item.settingsConnection", icon: "lan" },
      { page: "settings-thread", label: "sidebar.item.settingsThread", icon: "device_hub" },
      { page: "settings-device", label: "sidebar.item.settingsDevice", icon: "warning" },
    ],
  },
];

@customElement("sidebar-nav")
export class SidebarComponent extends LitElement {
  override createRenderRoot() {
    return this;
  }

  @property({ type: String }) currentPage: NavPage = "monitor-status";

  private readonly locale = createLocaleController(this);

  private readonly appState = new LitStoreController(
    this,
    store,
    (s) => ({
      brConnected: selectBrStatus(s)?.isConnected ?? false,
      threadState: selectThreadState(s),
      threadRunOnConnect: selectThreadRunOnConnect(s),
      nodesCount:
        (selectRouterTable(s)?.rows?.length ?? 0) + (selectChildTable(s)?.rows?.length ?? 0),
    }),
    shallowEqual
  );

  private _statusClass(): string {
    if (!this.appState.value.brConnected) return "status-role-disconnected";
    const s = this.appState.value.threadState?.toLowerCase();
    if (s === "child") return "status-role-child";
    if (s === "router") return "status-role-router";
    if (s === "leader") return "status-role-leader";
    return "status-role-disabled";
  }

  private _statusTitle(): string {
    if (!this.appState.value.brConnected) return t("common.state.disconnected");
    if (this.appState.value.threadState) return this.appState.value.threadState;
    return t("sidebar.status.disabled");
  }

  private _handlePrimaryClick(page: NavPage) {
    this._emitNavigate(page);
  }

  private _emitNavigate(page: NavPage) {
    this.dispatchEvent(new CustomEvent("navigate", { detail: page, bubbles: true, composed: true }));
  }

  render() {
    void this.locale.value;
    const statusClass = this._statusClass();
    const statusTitle = this._statusTitle();

    return html`<aside class="sidebar">
      <div class="sidebar-header">
        <div class="sidebar-brand">
          <div class="sidebar-logo">
            <span class="material-symbols-outlined">hub</span>
          </div>
          <span class="sidebar-brand-text">${t("sidebar.brand")}</span>
        </div>
      </div>
      <div class="sidebar-status">
        <div class="sidebar-status-text ${statusClass}">${statusTitle}</div>
      </div>
      <nav class="sidebar-nav">
        <div class="sidebar-nav-section">
          ${NAV_ITEMS.map(group => html`
            <div class="sidebar-nav-section-title">${t(group.label)}</div>
            ${group.items.map(item => html`
              <button class="sidebar-nav-item ${item.page === this.currentPage ? "active" : ""}" @click=${() => this._handlePrimaryClick(item.page)}>
                <span class="material-symbols-outlined">${item.icon}</span>
                ${t(item.label)}
              </button>
            `)}
          `)}
        </div>
      </nav>
      <div class="sidebar-footer">
      <div class="sidebar-user-box">
        <div class="sidebar-user-avatar">
          <span class="material-symbols-outlined">account_circle</span>
        </div>
        <div class="sidebar-user-info">
          <div class="sidebar-user-username">${t("sidebar.user.username")}</div>
          <div class="sidebar-user-name">${t("sidebar.user.name")}</div>
        </div>
      </div>
      </div>
    </aside>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "sidebar-nav": SidebarComponent;
  }
}

// Dashboard-Thread/frontend/src/shared/components/sidebar/sidebar.component.tsx
import { useState, useMemo } from "react";
import "@shared/components/sidebar/sidebar.style.scss";

export type NavPage =
  | "nodes"
  | "status"
  | "settings"
  | "settings-br"
  | "settings-openthread"
  | "settings-system";

interface SidebarProps {
  /** Chỉ hiện logo, ẩn nav và footer */
  logoOnly?: boolean;
  /** Trạng thái BR: false = xám; true = cam/tím/xanh lá/xanh dương theo state */
  brConnected?: boolean;
  /** State Thread: leader → xanh lá, router → tím, child → xanh dương; detached/disabled → cam */
  threadState?: string | null;
  /** Đã bật "tự chạy Thread" → màu theo state; chưa bật thì cam */
  threadRunOnConnect?: boolean;
  /** Tổng router + child (hiển thị bên cạnh "Nodes" khi có) */
  nodesCount?: number | null;
  currentPage?: NavPage;
  onNavigate?: (page: NavPage) => void;
}

const PRIMARY_ITEMS: { page: NavPage; label: string; icon: string }[] = [
  { page: "status", label: "Status", icon: "speed" },
  { page: "nodes", label: "Nodes", icon: "account_tree" },
  { page: "settings", label: "Settings", icon: "settings" },
];

const SETTINGS_ITEMS: { page: NavPage; label: string; icon: string }[] = [
  // BR Connection: đường mạng / LAN
  { page: "settings-br", label: "BR Connection", icon: "lan" },
  // OpenThread config: lưới / topology Thread
  { page: "settings-openthread", label: "OpenThread", icon: "device_hub" },
  // System: cảnh báo / vùng nguy hiểm
  { page: "settings-system", label: "System", icon: "warning" },
];

export default function Sidebar({
  logoOnly = false,
  brConnected = false,
  threadState = null,
  threadRunOnConnect = false,
  nodesCount = null,
  currentPage = "nodes",
  onNavigate = () => {},
}: SidebarProps) {
  const stateLower = threadState?.toLowerCase();
  const statusClass = !brConnected
    ? "status-disconnected"
    : stateLower === "child"
      ? "status-thread-blue"
      : stateLower === "router"
        ? "status-thread-purple"
        : stateLower === "leader"
          ? "status-thread-green"
          : "status-br";
  const statusTitle = !brConnected
    ? "Chưa kết nối BR"
    : threadState
      ? `BR đã kết nối, Thread: ${threadState}`
        : threadRunOnConnect
          ? "BR đã kết nối, đang chạy Thread"
          : "BR đã kết nối";

  const isSettingsPage = useMemo(
    () =>
      currentPage === "settings" ||
      currentPage === "settings-br" ||
      currentPage === "settings-openthread" ||
      currentPage === "settings-system",
    [currentPage],
  );
  const [settingsOpen, setSettingsOpen] = useState<boolean>(isSettingsPage);

  const handlePrimaryClick = (page: NavPage) => {
    if (page === "settings") {
      // Toggle dropdown; nếu đang ở trang settings thì chỉ gập/mở, không đổi section
      setSettingsOpen((open) => !open);
      if (!isSettingsPage) {
        onNavigate("settings-br");
      }
      return;
    }
    onNavigate(page);
  };

  return (
    <aside className="sidebar">
      <div className="sidebar-header">
        <div className="sidebar-logo">
          <span className="material-symbols-outlined">hub</span>
        </div>
        <div className="sidebar-brand-row">
          <span className="sidebar-brand-text">OpenThread</span>
          {!logoOnly && (
            <span
              className={`sidebar-status-dot ${statusClass}`}
              title={statusTitle}
              aria-label={statusTitle}
            />
          )}
        </div>
      </div>
      {!logoOnly && (
        <>
          <nav className="sidebar-nav">
            {PRIMARY_ITEMS.map(({ page, label, icon }) => (
              <button
                key={page}
                type="button"
                className={`sidebar-nav-item ${
                  page === "settings" ? (isSettingsPage ? "active" : "") : currentPage === page ? "active" : ""
                }`}
                onClick={() => handlePrimaryClick(page)}
                title={
                  page === "nodes" && nodesCount !== undefined && nodesCount !== null
                    ? `${label} (${nodesCount})`
                    : label
                }
              >
                <span className="material-symbols-outlined">{icon}</span>
                <span className="sidebar-nav-label">
                  {label}
                  {page === "nodes" && nodesCount !== undefined && nodesCount !== null
                    ? ` (${nodesCount})`
                    : ""}
                </span>
                {page === "settings" && (
                  <span
                    className={`material-symbols-outlined sidebar-expand-icon ${
                      settingsOpen ? "sidebar-expand-icon--open" : ""
                    }`}
                  >
                    expand_more
                  </span>
                )}
              </button>
            ))}

            <div className={`sidebar-section ${settingsOpen ? "sidebar-section--open" : "sidebar-section--closed"}`}>
              <div className="sidebar-section-items">
                {SETTINGS_ITEMS.map(({ page, label, icon }) => (
                  <button
                    key={page}
                    type="button"
                    className={`sidebar-nav-item sidebar-nav-item--nested ${
                      currentPage === page ? "active" : ""
                    }`}
                    onClick={() => onNavigate(page)}
                    title={label}
                  >
                    <span className="material-symbols-outlined sidebar-nav-nested-icon">{icon}</span>
                    <span className="sidebar-nav-label">{label}</span>
                  </button>
                ))}
              </div>
            </div>
          </nav>
          <div className="sidebar-footer">
            {/* Optional: Account or empty */}
          </div>
        </>
      )}
    </aside>
  );
}
