// Dashboard-Thread/frontend/src/components/Settings/OpenThreadConfigForm.tsx
import { useState, useEffect } from "react";
import { useWebSocketContext } from "../../hooks/useWebSocketContext";
import { useToast } from "../../contexts/ToastContext";
import "./OpenThreadConfigForm.scss";

export default function OpenThreadConfigForm() {
  const {
    serialStatus,
    otConfig,
    getOtConfig,
    setOtConfig,
    startThread,
    stopThread,
    threadRunOnConnect,
    getThreadRunOnConnect,
    setThreadRunOnConnect,
  } = useWebSocketContext();
  const { showToast } = useToast();
  const [panid, setPanid] = useState("");
  const [channel, setChannel] = useState<number>(11);
  const [networkName, setNetworkName] = useState("");
  const [extendedPanId, setExtendedPanId] = useState("");
  const [networkKey, setNetworkKey] = useState("");
  const [loading, setLoading] = useState(false);
  const [applying, setApplying] = useState(false);
  const [message, setMessage] = useState<{ type: "success" | "error"; text: string } | null>(null);
  const [showNetworkKey, setShowNetworkKey] = useState(false);

  const isConnected = serialStatus?.isConnected ?? false;

  // Tự lấy cấu hình từ thiết bị khi đã kết nối serial; load preference "tự chạy Thread" từ DB
  useEffect(() => {
    if (isConnected) {
      getOtConfig();
    }
    getThreadRunOnConnect();
  }, [isConnected, getOtConfig, getThreadRunOnConnect]);

  useEffect(() => {
    if (otConfig?.error) {
      setMessage({ type: "error", text: otConfig.error });
    } else if (otConfig) {
      if (otConfig.panid != null) setPanid(otConfig.panid);
      if (otConfig.channel != null) setChannel(otConfig.channel);
      if (otConfig.networkName != null) setNetworkName(otConfig.networkName);
      if (otConfig.extendedPanId != null) setExtendedPanId(otConfig.extendedPanId);
      if (otConfig.networkKey != null) setNetworkKey(otConfig.networkKey);
    }
  }, [otConfig]);

  const handleLoad = async () => {
    setMessage(null);
    setLoading(true);
    try {
      await getOtConfig();
    } finally {
      setLoading(false);
    }
  };

  const handleApply = async () => {
    setMessage(null);
    setApplying(true);
    const result = await setOtConfig({
      panid: panid.trim() || undefined,
      channel: channel >= 11 && channel <= 26 ? channel : undefined,
      networkName: networkName.trim() || undefined,
      extendedPanId: extendedPanId.trim() || undefined,
      networkKey: networkKey.trim() || undefined,
    });
    setApplying(false);
    if (result.success) {
      showToast("success", "Đã áp dụng cấu hình thành công.");
    } else {
      showToast("error", result.error ?? "Áp dụng thất bại.");
    }
  };

  return (
    <div className="form-page">
      <div className="form-page-header">
        <h2 className="form-page-title">Cấu hình mạng Thread</h2>
        <p className="form-page-description">
          Quản lý thông số kỹ thuật và trạng thái hoạt động của mạng Mesh trong môi trường OpenThread.
        </p>
      </div>

      {!isConnected && (
        <div className="form-page-alert form-page-alert-warn">
          Chưa kết nối BR. Vào Status/Nodes để kết nối rồi quay lại đây.
        </div>
      )}

      {message && (
        <div className={`form-page-alert form-page-alert-${message.type}`}>
          {message.text}
        </div>
      )}

      <div className="form-card ot-card">
        <div className="ot-card-header">
          <div className="ot-card-title">
            <span className="ot-card-title-icon" aria-hidden="true">
              <span className="material-symbols-outlined">device_hub</span>
            </span>
            <span>Thông số mạng</span>
          </div>
          <div className="ot-toggle-group">
            <span className="ot-toggle-label">Khởi động Thread</span>
            <label className="ot-toggle">
              <input
                type="checkbox"
                checked={threadRunOnConnect}
                onChange={async (e) => {
                  const newValue = e.target.checked;
                  setThreadRunOnConnect(newValue);

                  if (newValue) {
                    const result = await startThread();
                    if (result.success) {
                      showToast("success", "Đã khởi động Thread.");
                    } else {
                      showToast("error", result.error ?? "Không thể khởi động Thread.");
                      setThreadRunOnConnect(false);
                    }
                  } else {
                    const result = await stopThread();
                    if (result.success) {
                      showToast("success", "Đã dừng Thread.");
                    } else {
                      showToast("error", result.error ?? "Không thể dừng Thread.");
                      setThreadRunOnConnect(true);
                    }
                  }
                }}
                disabled={!isConnected}
              />
              <span className="ot-toggle-track" />
              <span className="ot-toggle-thumb" />
            </label>
          </div>
        </div>

        <div className="ot-card-body form-page-form">
          <div className="form-row-2">
            <div className="form-group ot-field-group">
              <label htmlFor="ot-panid">PAN ID</label>
              <div className="ot-input-wrap">
                <input
                  id="ot-panid"
                  type="text"
                  value={panid}
                  onChange={(e) => setPanid(e.target.value)}
                  placeholder="0x1986"
                  disabled={!isConnected}
                />
              </div>
            </div>
            <div className="form-group ot-field-group">
              <label htmlFor="ot-channel">Kênh (Channel)</label>
              <div className="ot-input-wrap">
                <input
                  id="ot-channel"
                  type="number"
                  min={11}
                  max={26}
                  value={channel}
                  onChange={(e) => setChannel(parseInt(e.target.value, 10) || 11)}
                  disabled={!isConnected}
                />
              </div>
            </div>
          </div>

          <div className="form-group ot-field-group">
            <label htmlFor="ot-networkname">Tên mạng (Network Name)</label>
            <div className="ot-input-wrap">
              <input
                id="ot-networkname"
                type="text"
                value={networkName}
                onChange={(e) => setNetworkName(e.target.value)}
                placeholder="OpenThread-Mesh"
                disabled={!isConnected}
              />
            </div>
          </div>

          <div className="form-group ot-field-group">
            <label htmlFor="ot-extendedpanid">Extended PAN ID</label>
            <div className="ot-input-wrap">
              <input
                id="ot-extendedpanid"
                type="text"
                value={extendedPanId}
                onChange={(e) => setExtendedPanId(e.target.value)}
                placeholder="DEADBEEF00112233"
                disabled={!isConnected}
              />
            </div>
          </div>

          <div className="form-group ot-field-group">
            <label htmlFor="ot-networkkey">Khóa mạng (Network Key)</label>
            <div className="ot-input-wrap">
              <input
                id="ot-networkkey"
                type={showNetworkKey ? "text" : "password"}
                value={networkKey}
                onChange={(e) => setNetworkKey(e.target.value)}
                placeholder="00112233445566778899AABBCCDDEEFF"
                disabled={!isConnected}
              />
              <button
                type="button"
                className="ot-eye-btn"
                onClick={() => setShowNetworkKey((prev) => !prev)}
                title={showNetworkKey ? "Ẩn khóa" : "Hiện khóa"}
              >
                <span className="material-symbols-outlined">
                  {showNetworkKey ? "visibility_off" : "visibility"}
                </span>
              </button>
            </div>
            <span className="ot-field-hint">Khóa mạng được mã hóa để đảm bảo an toàn.</span>
          </div>
        </div>

        <div className="ot-card-footer">
          <button
            type="button"
            className="form-btn form-btn--ghost"
            onClick={handleLoad}
            disabled={!isConnected || loading}
          >
            {loading ? "Đang tải…" : "Lấy lại"}
          </button>
          <button
            type="button"
            className="form-btn form-btn--primary"
            onClick={handleApply}
            disabled={!isConnected || applying}
          >
            {applying ? "Đang áp dụng…" : "Áp dụng"}
          </button>
        </div>
      </div>
    </div>
  );
}

// Dashboard-Thread/frontend/src/features/settings/components/openthread-config-form/openthread-config-form.component.ts
import { LitElement, html } from "lit";
import { customElement, property, state } from "lit/decorators.js";

import "@settings/components/openthread-config-form/openthread-config-form.style.scss";

@customElement("openthread-config-form")
export class OpenThreadConfigFormComponent extends LitElement {
  override createRenderRoot() {
    return this;
  }

  @property({ type: Boolean }) isConnected = false;
  @property({ type: Object }) otConfig: { panid?: string; channel?: number; networkName?: string; extendedPanId?: string; networkKey?: string; error?: string } | null = null;
  @property({ type: Boolean }) threadRunOnConnect = false;
  @property({ attribute: false }) getOtConfig: () => Promise<unknown> = async () => null;
  @property({ attribute: false }) setOtConfig: (data: { panid?: string; channel?: number; networkName?: string; extendedPanId?: string; networkKey?: string }) => Promise<{ success: boolean; error?: string }> = async () => ({ success: false });
  @property({ attribute: false }) startThread: () => Promise<{ success: boolean; error?: string }> = async () => ({ success: false });
  @property({ attribute: false }) stopThread: () => Promise<{ success: boolean; error?: string }> = async () => ({ success: false });
  @property({ attribute: false }) getThreadRunOnConnect: () => void = () => {};
  @property({ attribute: false }) setThreadRunOnConnect: (run: boolean) => void = () => {};
  @property({ attribute: false }) showToast: (type: "success" | "error", message: string) => void = () => {};

  @state() private panid = "";
  @state() private channel = 11;
  @state() private networkName = "";
  @state() private extendedPanId = "";
  @state() private networkKey = "";
  @state() private loading = false;
  @state() private applying = false;
  @state() private message: { type: "success" | "error"; text: string } | null = null;
  @state() private showNetworkKey = false;

  override connectedCallback() {
    super.connectedCallback();
    if (this.isConnected) this.getOtConfig();
    this.getThreadRunOnConnect();
  }

  override willUpdate(changed: Map<string, unknown>) {
    if (changed.has("otConfig") && this.otConfig) {
      if (this.otConfig.error) this.message = { type: "error", text: this.otConfig.error };
      else {
        if (this.otConfig.panid != null) this.panid = this.otConfig.panid;
        if (this.otConfig.channel != null) this.channel = this.otConfig.channel;
        if (this.otConfig.networkName != null) this.networkName = this.otConfig.networkName;
        if (this.otConfig.extendedPanId != null) this.extendedPanId = this.otConfig.extendedPanId;
        if (this.otConfig.networkKey != null) this.networkKey = this.otConfig.networkKey;
      }
    }
  }

  private async _handleLoad() {
    this.message = null;
    this.loading = true;
    try {
      await this.getOtConfig();
    } finally {
      this.loading = false;
    }
  }

  private async _handleApply() {
    this.message = null;
    this.applying = true;
    const result = await this.setOtConfig({
      panid: this.panid.trim() || undefined,
      channel: this.channel >= 11 && this.channel <= 26 ? this.channel : undefined,
      networkName: this.networkName.trim() || undefined,
      extendedPanId: this.extendedPanId.trim() || undefined,
      networkKey: this.networkKey.trim() || undefined,
    });
    this.applying = false;
    if (result.success) this.showToast("success", "Đã áp dụng cấu hình thành công.");
    else this.showToast("error", result.error ?? "Áp dụng thất bại.");
  }

  private async _handleThreadToggle(e: Event) {
    const newValue = (e.target as HTMLInputElement).checked;
    this.setThreadRunOnConnect(newValue);
    if (newValue) {
      const result = await this.startThread();
      if (result.success) this.showToast("success", "Đã khởi động Thread.");
      else {
        this.showToast("error", result.error ?? "Không thể khởi động Thread.");
        this.setThreadRunOnConnect(false);
      }
    } else {
      const result = await this.stopThread();
      if (result.success) this.showToast("success", "Đã dừng Thread.");
      else {
        this.showToast("error", result.error ?? "Không thể dừng Thread.");
        this.setThreadRunOnConnect(true);
      }
    }
  }

  render() {
    return html`
      <div class="form-page">
        <div class="form-page-header">
          <h2 class="form-page-title">Cấu hình mạng Thread</h2>
          <p class="form-page-description">
            Quản lý thông số kỹ thuật và trạng thái hoạt động của mạng Mesh trong môi trường OpenThread.
          </p>
        </div>
        ${!this.isConnected
          ? html`<div class="form-page-alert form-page-alert-warn">Chưa kết nối BR. Vào Status/Nodes để kết nối rồi quay lại đây.</div>`
          : ""}
        ${this.message ? html`<div class="form-page-alert form-page-alert-${this.message.type}">${this.message.text}</div>` : ""}
        <div class="form-card ot-card">
          <div class="ot-card-header">
            <div class="ot-card-title">
              <span class="ot-card-title-icon" aria-hidden="true">
                <span class="material-symbols-outlined">device_hub</span>
              </span>
              <span>Thông số mạng</span>
            </div>
            <div class="ot-toggle-group">
              <span class="ot-toggle-label">Khởi động Thread</span>
              <label class="ot-toggle">
                <input
                  type="checkbox"
                  ?checked=${this.threadRunOnConnect}
                  @change=${this._handleThreadToggle}
                  ?disabled=${!this.isConnected}
                />
                <span class="ot-toggle-track"></span>
                <span class="ot-toggle-thumb"></span>
              </label>
            </div>
          </div>
          <div class="ot-card-body form-page-form">
            <div class="form-row-2">
              <div class="form-group ot-field-group">
                <label for="ot-panid">PAN ID</label>
                <div class="ot-input-wrap">
                  <input
                    id="ot-panid"
                    type="text"
                    .value=${this.panid}
                    @input=${(e: Event) => (this.panid = (e.target as HTMLInputElement).value)}
                    placeholder="0x1986"
                    ?disabled=${!this.isConnected}
                  />
                </div>
              </div>
              <div class="form-group ot-field-group">
                <label for="ot-channel">Kênh (Channel)</label>
                <div class="ot-input-wrap">
                  <input
                    id="ot-channel"
                    type="number"
                    min="11"
                    max="26"
                    .value=${this.channel}
                    @input=${(e: Event) => (this.channel = parseInt((e.target as HTMLInputElement).value, 10) || 11)}
                    ?disabled=${!this.isConnected}
                  />
                </div>
              </div>
            </div>
            <div class="form-group ot-field-group">
              <label for="ot-networkname">Tên mạng (Network Name)</label>
              <div class="ot-input-wrap">
                <input
                  id="ot-networkname"
                  type="text"
                  .value=${this.networkName}
                  @input=${(e: Event) => (this.networkName = (e.target as HTMLInputElement).value)}
                  placeholder="OpenThread-Mesh"
                  ?disabled=${!this.isConnected}
                />
              </div>
            </div>
            <div class="form-group ot-field-group">
              <label for="ot-extendedpanid">Extended PAN ID</label>
              <div class="ot-input-wrap">
                <input
                  id="ot-extendedpanid"
                  type="text"
                  .value=${this.extendedPanId}
                  @input=${(e: Event) => (this.extendedPanId = (e.target as HTMLInputElement).value)}
                  placeholder="DEADBEEF00112233"
                  ?disabled=${!this.isConnected}
                />
              </div>
            </div>
            <div class="form-group ot-field-group">
              <label for="ot-networkkey">Khóa mạng (Network Key)</label>
              <div class="ot-input-wrap">
                <input
                  id="ot-networkkey"
                  type=${this.showNetworkKey ? "text" : "password"}
                  .value=${this.networkKey}
                  @input=${(e: Event) => (this.networkKey = (e.target as HTMLInputElement).value)}
                  placeholder="00112233445566778899AABBCCDDEEFF"
                  ?disabled=${!this.isConnected}
                />
                <button
                  type="button"
                  class="ot-eye-btn"
                  @click=${() => (this.showNetworkKey = !this.showNetworkKey)}
                  title=${this.showNetworkKey ? "Ẩn khóa" : "Hiện khóa"}
                >
                  <span class="material-symbols-outlined">${this.showNetworkKey ? "visibility_off" : "visibility"}</span>
                </button>
              </div>
              <span class="ot-field-hint">Khóa mạng được mã hóa để đảm bảo an toàn.</span>
            </div>
          </div>
          <div class="ot-card-footer">
            <button type="button" class="form-btn form-btn--ghost" @click=${this._handleLoad} ?disabled=${!this.isConnected || this.loading}>
              ${this.loading ? "Đang tải…" : "Lấy lại"}
            </button>
            <button type="button" class="form-btn form-btn--primary" @click=${this._handleApply} ?disabled=${!this.isConnected || this.applying}>
              ${this.applying ? "Đang áp dụng…" : "Áp dụng"}
            </button>
          </div>
        </div>
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "openthread-config-form": OpenThreadConfigFormComponent;
  }
}
